# ============================================================================
# Test Script for rRegressionViewer Package
# ============================================================================
#
# Purpose:
#   This script demonstrates how to use the rRegressionViewer package to
#   compare and visualize multiple regression models side-by-side. The package
#   provides an interactive Shiny application for exploring regression results.
#
# Author: Matthias Uckert
# Date: 2025-10-18
# ============================================================================

# Load the rRegressionViewer package
# (Uncomment if needed: library(rRegressionViewer))

# ----------------------------------------------------------------------------
# Run Regression Comparison Viewer
# ----------------------------------------------------------------------------
#
# This function launches an interactive Shiny application that allows you to:
#   - View multiple regression models in a formatted comparison table
#   - Apply custom formatting to coefficients, standard errors, and statistics
#   - Export results to Excel or other formats
#   - Toggle significance indicators and formatting options
#
# Parameters:
#   .path: Full file path to an RDS file containing regression model results.
#          The RDS file should contain a list or collection of fitted model
#          objects (e.g., lm, glm, or similar regression model types).
#
#   .dir:  Output directory path where comparison files and exports will be
#          saved. This directory will store any Excel files, templates, or
#          other output generated by the comparison viewer.
#
# Example RDS structure:
#   The input RDS should contain named regression models, such as:
#   list(
#     Model1 = lm(y ~ x1 + x2, data = df),
#     Model2 = lm(y ~ x1 + x2 + x3, data = df),
#     ...
#   )
# ----------------------------------------------------------------------------
run_regression_comparison(
  .path = "/Users/matthiasuckert/RProjects/Projects/pTerminology/2_output/31-Regressions/Output/FinalRegressions.rds",
  .dir = "/Users/matthiasuckert/Downloads/TEST"
)

